# Generated by Django 4.1.3 on 2023-01-09 05:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('victim_name', models.CharField(max_length=100)),
                ('victim_id', models.IntegerField(max_length=8)),
                ('crime_location', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=100)),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.crime')),
            ],
        ),
        migrations.CreateModel(
            name='Arrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrest_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('suspect_name', models.CharField(max_length=100)),
                ('suspect_id', models.IntegerField(max_length=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('crime_location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('crime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.crime')),
                ('incidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.report')),
            ],
        ),
    ]
