# Generated by Django 4.1.3 on 2023-01-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrest',
            name='incidence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.report'),
        ),
    ]
