# Generated by Django 4.1.3 on 2022-12-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_arrest_user_alter_report_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
